@echo off
REM Auto-generated by req2toml from commands.txt

echo ^> uv run python Download_Song_Models.py --model songgen_large
uv run python Download_Song_Models.py --model songgen_large
if %ERRORLEVEL% neq 0 echo [WARNING] Command exited with code %ERRORLEVEL%
