@echo off
setlocal EnableDelayedExpansion
REM Auto-generated by req2toml
REM These commands must be run after uv sync

REM Resolve uv path — prefer PATH, fallback to full path
set "UV=uv"
where uv >nul 2>&1
if %ERRORLEVEL% neq 0 (
    if exist "%USERPROFILE%\.local\bin\uv.exe" (
        set "UV=%USERPROFILE%\.local\bin\uv.exe"
    ) else (
        echo [ERROR] uv not found. Run setup_uv.cmd first.
        exit /b 1
    )
)

echo ^> %UV% pip install flash_attn@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/flash_attn-2.8.2-cp310-cp310-win_amd64.whl ; sys_platform == 'win32'
%UV% pip install flash_attn@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/flash_attn-2.8.2-cp310-cp310-win_amd64.whl ; sys_platform == 'win32'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% pip install flash_attn@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/flash_attn-2.8.2-cp310-cp310-linux_x86_64.whl ; sys_platform == 'linux'
%UV% pip install flash_attn@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/flash_attn-2.8.2-cp310-cp310-linux_x86_64.whl ; sys_platform == 'linux'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% pip install xformers@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/xformers-0.0.33+c159edc0.d20250906-cp39-abi3-win_amd64.whl ; sys_platform == 'win32'
%UV% pip install xformers@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/xformers-0.0.33+c159edc0.d20250906-cp39-abi3-win_amd64.whl ; sys_platform == 'win32'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% pip install xformers@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/xformers-0.0.33+c159edc0.d20250906-cp39-abi3-linux_x86_64.whl ; sys_platform == 'linux'
%UV% pip install xformers@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/xformers-0.0.33+c159edc0.d20250906-cp39-abi3-linux_x86_64.whl ; sys_platform == 'linux'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% pip install sageattention@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/sageattention-2.2.0-cp39-abi3-linux_x86_64.whl ; sys_platform == 'linux'
%UV% pip install sageattention@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/sageattention-2.2.0-cp39-abi3-linux_x86_64.whl ; sys_platform == 'linux'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% pip install sageattention@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/sageattention-2.2.0-cp39-abi3-win_amd64.whl ; sys_platform == 'win32'
%UV% pip install sageattention@ https://huggingface.co/MonsterMMORPG/Wan_GGUF/resolve/main/sageattention-2.2.0-cp39-abi3-win_amd64.whl ; sys_platform == 'win32'
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

echo ^> %UV% run python Download_Song_Models.py --model songgen_large
%UV% run python Download_Song_Models.py --model songgen_large
if !ERRORLEVEL! neq 0 echo [WARNING] Command exited with code !ERRORLEVEL!

endlocal