@echo off
REM ============================================================
REM  setup_uv.cmd
REM  Install uv (no Python required), then uv sync
REM
REM  Pre-requisite: pyproject.toml must exist in the same folder.
REM  Generate it with: python req2toml.py requirements.txt
REM ============================================================

setlocal EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
set "UV_BIN=%USERPROFILE%\.local\bin\uv.exe"

echo.
echo ========================================
echo   uv Installer + Sync
echo ========================================
echo.

REM --------------------------------------------------
REM 0. Set uv environment flags for Windows
REM --------------------------------------------------
set UV_SKIP_WHEEL_FILENAME_CHECK=1
set UV_LINK_MODE=copy

REM --------------------------------------------------
REM 1. Resolve uv path — prefer PATH, fallback to full path
REM --------------------------------------------------
set "UV=uv"
where uv >nul 2>&1
if %ERRORLEVEL% neq 0 (
    if exist "%UV_BIN%" (
        set "UV=%UV_BIN%"
        echo [OK] uv found at %UV_BIN%
    ) else (
        goto :install_uv
    )
) else (
    echo [OK] uv is on PATH:
)
!UV! --version
echo.
goto :check_toml

REM --------------------------------------------------
REM 2. Install uv via the official standalone installer
REM --------------------------------------------------
:install_uv
echo [*] Installing uv via astral.sh standalone installer ...
echo.

powershell -NoProfile -ExecutionPolicy ByPass -Command "irm https://astral.sh/uv/install.ps1 | iex"

if %ERRORLEVEL% neq 0 (
    echo.
    echo [ERROR] uv installation failed.
    exit /b 1
)

echo.
echo [OK] uv installer finished.

REM Use full path since it won't be on PATH yet
set "UV=%UV_BIN%"
if not exist "!UV!" (
    echo [ERROR] uv binary not found at !UV!
    exit /b 1
)
echo [OK] uv is available:
!UV! --version

REM --------------------------------------------------
REM 3. Verify pyproject.toml exists
REM --------------------------------------------------
:check_toml
if not exist "%SCRIPT_DIR%pyproject.toml" (
    echo.
    echo [ERROR] pyproject.toml not found in %SCRIPT_DIR%
    echo         Run req2toml.py first to generate it from requirements.txt.
    exit /b 1
)

REM --------------------------------------------------
REM 4. Remove stale .venv if interpreter is broken
REM --------------------------------------------------
if exist "%SCRIPT_DIR%.venv\Scripts\python.exe" (
    "%SCRIPT_DIR%.venv\Scripts\python.exe" -c "pass" >nul 2>&1
    if !ERRORLEVEL! neq 0 (
        echo [*] Removing stale .venv ...
        rmdir /s /q "%SCRIPT_DIR%.venv"
    )
)

REM --------------------------------------------------
REM 5. uv sync — install all dependencies
REM --------------------------------------------------
echo.
echo [*] Running uv sync ...
echo.
cd /d "%SCRIPT_DIR%"
!UV! sync --no-install-project

if %ERRORLEVEL% neq 0 (
    echo.
    echo [ERROR] uv sync failed. See output above.
    exit /b 1
)

REM --------------------------------------------------
REM 6. Run post-install commands (generated by req2toml)
REM --------------------------------------------------
if exist "%SCRIPT_DIR%post_install.cmd" (
    echo.
    echo [*] Running post-install commands ...
    echo.
    call "%SCRIPT_DIR%post_install.cmd"
)

echo.
echo ========================================
echo   All done! Dependencies are synced.
echo ========================================
echo.

endlocal
